import type { Settings } from "./types.js";

export const defaultSettings: Settings = {
  botEnabled: false,
  paperMode: true,
  autoDiscoverMarket: true,
  manualMarketUrl: "",
  entryStartSeconds: 20,
  entryEndSeconds: 180,
  minBtcMoveBps: 4,
  velocityLookbackSeconds: 15,
  minBtcVelocityBps: 1.5,
  reversalExitBps: 0,
  maxEntryPrice: 0.62,
  minEdgeBps: 0,
  maxPositionUsdc: 100,
  kellyEnabled: true,
  kellyFraction: 0.5,
  kellyLookbackTrades: 100,
  kellyMinTrades: 20,
  kellyFallbackPct: 1,
  kellyMaxPct: 5,
  maxShares: 250,
  depthUsageRatio: 0.25,
  minOrderUsdc: 10,
  maxEntrySlippageCents: 3,
  maxExitSlippageCents: 8,
  maxSpreadCents: 4,
  repriceIntervalMs: 1000,
  takeProfitCents: 7,
  stopLossCents: 8,
  maxHoldSeconds: 180,
  exitBeforeResolveSeconds: 35,
  panicHedgeEnabled: true,
  panicLossCents: 12,
  panicBtcReversalBps: 0,
  minExitFillRatio: 0.4,
  hedgeSizeRatio: 1,
  maxHedgePrice: 0.65,
  maxHedgeSlippageCents: 5,
  paperBalance: 10000,
  feeBps: 0,
  enableSnapshots: true,
  snapshotIntervalMs: 1000,
  enableOrderbookLogs: true,
  keepMaxLogMb: 500
};
