import type { Settings } from "./types.js";

export const defaultSettings: Settings = {
  botEnabled: false,
  paperMode: true,
  autoDiscoverMarket: true,
  manualMarketUrl: "",
  entryStartSeconds: 25,
  entryEndSeconds: 120,
  minBtcMoveBps: 3,
  velocityLookbackSeconds: 15,
  minBtcVelocityBps: 1,
  maxEntryPrice: 0.78,
  maxPositionUsdc: 100,
  kellyEnabled: true,
  kellyFraction: 0.5,
  kellyLookbackTrades: 100,
  kellyMinTrades: 20,
  kellyFallbackPct: 10,
  kellyMaxPct: 20,
  maxShares: 250,
  depthUsageRatio: 0.35,
  goodSpreadCents: 1,
  okSpreadCents: 4,
  minDepthToKellyRatio: 0.35,
  thinDepthMultiplier: 0.6,
  okDepthMultiplier: 0.85,
  minOrderUsdc: 1,
  maxEntrySlippageCents: 3,
  maxSpreadCents: 5,
  repriceIntervalMs: 1000,
  panicHedgeEnabled: true,
  panicLossCents: 18,
  hedgeSizeRatio: 0.5,
  minHedgeImprovementPct: 15,
  maxHedgePrice: 0.6,
  maxHedgeSlippageCents: 5,
  paperBalance: 10000,
  feeBps: 0,
  enableSnapshots: true,
  snapshotIntervalMs: 1000,
  enableOrderbookLogs: true,
  keepMaxLogMb: 500
};
