import type { Settings } from "./types.js";

export const defaultSettings: Settings = {
  botEnabled: false,
  paperMode: true,
  autoDiscoverMarket: true,
  manualMarketUrl: "",
  entryStartSeconds: 30,
  entryEndSeconds: 60,
  minBtcMoveBps: 3,
  velocityLookbackSeconds: 15,
  minBtcVelocityBps: 1,
  maxEntryPrice: 0.78,
  minEdgeBps: 0,
  maxPositionUsdc: 100,
  kellyEnabled: true,
  kellyFraction: 0.5,
  kellyLookbackTrades: 100,
  kellyMinTrades: 20,
  kellyFallbackPct: 5,
  kellyMaxPct: 12,
  maxShares: 250,
  depthUsageRatio: 0.25,
  goodSpreadCents: 1,
  okSpreadCents: 4,
  minDepthToKellyRatio: 0.5,
  thinDepthMultiplier: 0.4,
  okDepthMultiplier: 0.7,
  minOrderUsdc: 10,
  maxEntrySlippageCents: 3,
  maxSpreadCents: 5,
  repriceIntervalMs: 1000,
  panicHedgeEnabled: true,
  panicLossCents: 18,
  hedgeSizeRatio: 0.5,
  maxHedgePrice: 0.6,
  maxHedgeSlippageCents: 5,
  paperBalance: 10000,
  feeBps: 5,
  enableSnapshots: true,
  snapshotIntervalMs: 1000,
  enableOrderbookLogs: true,
  keepMaxLogMb: 500
};
